# Generated by Django 4.1.6 on 2023-02-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="added_by",
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
